boxes:
  bedrock:
    win-markers:
      - bedrock_win
    display:
      scoreboard:
        display-name: "&6Bedrock Wins"
        entry-name: "&eWins"
      bossbar:
        title-label: "Bedrock Wins"
  sandbox:
    win-markers:
      - "[s2e-sand-box] win-up"
      - "win-up"
    display:
      scoreboard:
        display-name: "&6Sandbox Wins"
        entry-name: "&eWins"
      bossbar:
        title-label: "Sandbox Wins"

display:
  mode: BOSSBAR
  scoreboard:
    objective-name: bedrock_wins
    display-slot: SIDEBAR
  bossbar:
    color: YELLOW
    style: SOLID
    text-colors:
      negative: "&c"
      zero: "&6"
      positive: "&a"
    progress:
      enabled: true

messages:
  prefix: "&8[&6BedrockWins&8] &r"
